# 开发环境配置
server:
  port: 80


logging:
     path: C:/logs
     logFileLeve: ERROR
     jdbcUrl: jdbc:mysql://localhost:3306/lottery_pay_local?characterEncoding=utf8&useSSL=false
     username: '[密文]tloCKldFYbN9UsbK+OFOOg=='
     password: '[密文]avsf77v6E93FvOBqTzSzdA=='
     dbPollName: logBackPayServHikariPool
     level:
         dc.pay: DEBUG
         org.springframework.web: INFO